New upstream version 2.7.0

diff --git a/tests/regression/tools/save-load/test_load b/tests/regression/tools/save-load/test_load
--- a/tests/regression/tools/save-load/test_load
+++ b/tests/regression/tools/save-load/test_load
@@ -29,7 +29,7 @@ EVENT_NAME="tp:tptest"
 
 DIR=$(readlink -f $TESTDIR)
 
-NUM_TESTS=21
+NUM_TESTS=28
 
 source $TESTDIR/utils/utils.sh
 
@@ -38,23 +38,13 @@ plan_tests $NUM_TESTS
 
 print_test_banner "$TEST_DESC"
 
-function disable_event()
-{
-	local sess_name="$1"
-	local chan_name="$2"
-	local event_name="$3"
-
-	$TESTDIR/../src/bin/lttng/$LTTNG_BIN disable-event "$event_name" -s $sess_name -c $chan_name -u >/dev/null 2>&1
-	ok $? "Disable event $event_name for session $sess_name"
-}
-
 function test_basic_load()
 {
 	diag "Test basic load"
 
 	lttng_load "-i $CURDIR/$SESSION_NAME.lttng"
 
-	destroy_lttng_session $SESSION_NAME
+	destroy_lttng_session_ok $SESSION_NAME
 }
 
 function test_complex_load()
@@ -70,9 +60,9 @@ function test_complex_load()
 
 	# Once loaded, we are suppose to be able to disable certain events/channels
 	# thus having a confirmation that it's valid
-	disable_event $sess chan1 uevent1
-	disable_event $sess chan2 uevent2
-	disable_event $sess chan3 uevent3*
+	disable_ust_lttng_event $sess uevent1 chan1
+	disable_ust_lttng_event $sess uevent2 chan2
+	disable_ust_lttng_event $sess uevent3* chan3
 
 	disable_ust_lttng_channel $sess chan1
 	disable_ust_lttng_channel $sess chan2
@@ -90,9 +80,9 @@ function test_complex_load()
 	else
 	    fail "Disabled event is loaded in disabled state"
 	fi
-	destroy_lttng_session $sess
+	destroy_lttng_session_ok $sess
 
-	stop_lttng_relayd_nocheck
+	stop_lttng_relayd
 }
 
 function test_all_load()
@@ -105,10 +95,11 @@ function test_all_load()
 
 	lttng_load "-a -i $CURDIR"
 
-	destroy_lttng_session $SESSION_NAME
-	destroy_lttng_session "$SESSION_NAME-complex"
+	destroy_lttng_session_ok $SESSION_NAME
+	destroy_lttng_session_ok "$SESSION_NAME-complex"
+	destroy_lttng_session_ok "$SESSION_NAME-trackers"
 
-	stop_lttng_relayd_nocheck
+	stop_lttng_relayd
 }
 
 function test_overwrite()
@@ -120,7 +111,32 @@ function test_overwrite()
 	# This one should succeed
 	lttng_load "-f -i $CURDIR $SESSION_NAME"
 
-	destroy_lttng_session $SESSION_NAME
+	destroy_lttng_session_ok $SESSION_NAME
+}
+
+function test_trackers()
+{
+	diag "Test trackers loading"
+
+	lttng_load "-i $CURDIR/$SESSION_NAME-trackers.lttng"
+
+	diag "Test pid tracker"
+	local mi_output_file=$(mktemp)
+	if [ $? -ne 0 ]; then
+		break;
+	fi
+	$TESTDIR/../src/bin/lttng/$LTTNG_BIN --mi XML list "$SESSION_NAME-trackers" > $mi_output_file
+	mi_result=$($CURDIR/../mi/extract_xml -e $mi_output_file "//command/output/sessions/session/domains/domain/trackers/pid_tracker/targets/pid_target")
+	if [[ $mi_result = "true" ]]; then
+	    ok 0 "Pid target is present"
+	else
+	    fail "Pid target missing"
+	fi
+
+	# Test to remove the target just to make sure
+	lttng_untrack_ok "-p 666 -u -s $SESSION_NAME-trackers"
+
+	destroy_lttng_session_ok "$SESSION_NAME-trackers"
 }
 
 start_lttng_sessiond
@@ -130,6 +146,7 @@ TESTS=(
 	test_complex_load
 	test_all_load
 	test_overwrite
+	test_trackers
 )
 
 for fct_test in ${TESTS[@]};
